version: '3'
services:
  php:
    image: yiisoftware/yii2-php:7.1-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8000:80'
    environment:
      XDEBUG_CONFIG: "remote_host=host.docker.internal remote_enable=1"
      PHP_IDE_CONFIG: "serverName=Docker"
    networks:
      - internal
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: yii2calendar
#  php-fpm:
#    build:
#      context: docker/php-fpm
#    volumes:
#      - ./:/var/www
#    environment:
#      XDEBUG_CONFIG: "remote_host=host.docker.internal remote_enable=1"
#      PHP_IDE_CONFIG: "serverName=Docker"
#    networks:
#      - internal
#  nginx:
#    build:
#      context: docker/nginx
#    volumes:
#      - ./:/var/www
#    ports:
#      - "80:80"
#    depends_on:
#      - php-fpm
#    networks:
#      - internal
networks:
  internal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.220.0/28